import type { Metadata } from "next";
import { Teko } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const teko = Teko({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(teko.className, "bg-[#0a0a0a] text-white")}>
        {children}
      </body>
    </html>
  );
}
